[package]
name = "gen_data"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rayon = "1.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
[dependencies.uuid]
features = ["serde"]